/**
 * WFC Approach 1: Full Path Generation
 *
 * Replace A* entirely. Each edge's path is generated by WFC tile collapse.
 * Nodes and connections are pre-collapsed, then WFC propagates path tiles
 * outward from source connections toward target connections.
 *
 * Strategy:
 * 1. Pre-collapse node, blocked, connection cells
 * 2. For each edge: seed source/target connection tiles with directional constraints
 * 3. Use guided WFC (biased toward target) to grow path from source to target
 * 4. Once path connects, freeze those cells and move to next edge
 */

import type { NodeDef, EdgeDef, ConnectionPoint, ScenarioResult, Grid2D } from './grid2d.js';
import { createGrid, setCell, getCell, distributeConnections } from './grid2d.js';
import {
  type WfcGrid, type WfcCell, type TileType, type Dir,
  createWfcGrid, collapseCell, getWfcCell, propagate,
  TILE_CONNECTIONS, DIR_OFFSET, OPPOSITE, ALL_DIRS, ROUTING_TILES,
  wfcToGrid2D,
} from './wfc-core.js';

// Re-use connection computation from grid2d
type Side = 'top' | 'bottom' | 'left' | 'right';

function facingSide(a: NodeDef, b: NodeDef): Side {
  const dx = (b.col + b.w / 2) - (a.col + a.w / 2);
  const dy = (b.row + b.h / 2) - (a.row + a.h / 2);
  if (Math.abs(dx) >= Math.abs(dy)) return dx >= 0 ? 'right' : 'left';
  return dy >= 0 ? 'bottom' : 'top';
}

function computeConnections(nodes: NodeDef[], edges: EdgeDef[]): ConnectionPoint[] {
  const nodeMap = new Map<number, NodeDef>();
  for (const n of nodes) nodeMap.set(n.id, n);

  interface SideEntry { edgeId: number; otherNode: NodeDef; otherNodeId: number }
  const sideGroups = new Map<string, SideEntry[]>();

  for (const e of edges) {
    const src = nodeMap.get(e.source);
    const tgt = nodeMap.get(e.target);
    if (!src || !tgt) continue;

    const srcSide = facingSide(src, tgt);
    const tgtSide = facingSide(tgt, src);

    const srcKey = `${e.source}:${srcSide}`;
    if (!sideGroups.has(srcKey)) sideGroups.set(srcKey, []);
    sideGroups.get(srcKey)!.push({ edgeId: e.id, otherNode: tgt, otherNodeId: e.target });

    const tgtKey = `${e.target}:${tgtSide}`;
    if (!sideGroups.has(tgtKey)) sideGroups.set(tgtKey, []);
    sideGroups.get(tgtKey)!.push({ edgeId: e.id, otherNode: src, otherNodeId: e.source });
  }

  const connections: ConnectionPoint[] = [];

  for (const [key, entries] of sideGroups) {
    const colonIdx = key.lastIndexOf(':');
    const nodeId = parseInt(key.slice(0, colonIdx));
    const side = key.slice(colonIdx + 1) as Side;
    const node = nodeMap.get(nodeId)!;

    if (side === 'left' || side === 'right') {
      entries.sort((a, b) => (a.otherNode.row + a.otherNode.h / 2) - (b.otherNode.row + b.otherNode.h / 2));
    } else {
      entries.sort((a, b) => (a.otherNode.col + a.otherNode.w / 2) - (b.otherNode.col + b.otherNode.w / 2));
    }

    let fixedCoord: number;
    let perpStart: number;
    let perpLen: number;

    switch (side) {
      case 'right':  fixedCoord = node.col + node.w; perpStart = node.row; perpLen = node.h; break;
      case 'left':   fixedCoord = node.col - 1;      perpStart = node.row; perpLen = node.h; break;
      case 'bottom': fixedCoord = node.row + node.h;  perpStart = node.col; perpLen = node.w; break;
      case 'top':    fixedCoord = node.row - 1;       perpStart = node.col; perpLen = node.w; break;
    }

    const positions = distributeConnections(perpStart, perpLen, entries.length);

    for (let i = 0; i < entries.length; i++) {
      const entry = entries[i]!;
      const pos = positions[i]!;
      const otherLabel = nodeMap.get(entry.otherNodeId)?.label ?? '';
      if (side === 'left' || side === 'right') {
        connections.push({ nodeId, edgeId: entry.edgeId, col: fixedCoord, row: pos, side, otherNodeId: entry.otherNodeId, otherNodeLabel: otherLabel });
      } else {
        connections.push({ nodeId, edgeId: entry.edgeId, col: pos, row: fixedCoord, side, otherNodeId: entry.otherNodeId, otherNodeLabel: otherLabel });
      }
    }
  }

  return connections;
}

/** Direction a connection faces OUTWARD from the node. */
function connOutDir(side: Side): Dir {
  switch (side) {
    case 'right': return 'right';
    case 'left':  return 'left';
    case 'bottom': return 'down';
    case 'top':   return 'up';
  }
}

/** Tiles that connect in a given direction. */
function tilesConnecting(dir: Dir): TileType[] {
  return ROUTING_TILES.filter(t => TILE_CONNECTIONS[t].has(dir));
}

/**
 * Guided WFC path: grow a path from (sc,sr) to (tc,tr) using constrained collapse.
 * Instead of random entropy selection, we use BFS-like wavefront from source
 * biased toward cells closer to target.
 */
function growPath(
  wfc: WfcGrid,
  sc: number, sr: number, sourceSide: Side,
  tc: number, tr: number, targetSide: Side,
  edgeId: number,
): boolean {
  // BFS wavefront from source toward target
  const visited = new Set<string>();
  const key = (c: number, r: number) => `${c}:${r}`;

  // Priority queue (simple sorted array) biased toward target
  const queue: { col: number; row: number; dist: number }[] = [];
  const enqueue = (c: number, r: number) => {
    const d = Math.abs(c - tc) + Math.abs(r - tr);
    queue.push({ col: c, row: r, dist: d });
    queue.sort((a, b) => a.dist - b.dist);
  };

  // Start from source connection's outward neighbour
  const srcOut = connOutDir(sourceSide);
  const [sdc, sdr] = DIR_OFFSET[srcOut];
  const startCol = sc + sdc;
  const startRow = sr + sdr;

  // Target approach cell
  const tgtIn = connOutDir(targetSide);
  const [tdc, tdr] = DIR_OFFSET[tgtIn];
  const goalCol = tc + tdc;
  const goalRow = tr + tdr;

  // Check if start/goal are valid
  const startCell = getWfcCell(wfc, startCol, startRow);
  const goalCell = getWfcCell(wfc, goalCol, goalRow);
  if (!startCell || !goalCell) return false;

  enqueue(startCol, startRow);

  let iterations = 0;
  const maxIter = wfc.cols * wfc.rows * 4;

  while (queue.length > 0 && iterations < maxIter) {
    iterations++;
    const { col, row } = queue.shift()!;
    const k = key(col, row);
    if (visited.has(k)) continue;
    visited.add(k);

    const cell = getWfcCell(wfc, col, row)!;
    if (cell.collapsed !== null && cell.collapsed !== 'empty') continue; // already used
    if (cell.options.size === 0) continue;

    // Filter to only tiles that connect toward our path
    // We need tiles that connect back toward the previous cell AND toward the target
    const routingOptions = [...cell.options].filter(t =>
      t !== 'empty' && t !== 'node' && t !== 'blocked' && t !== 'conn'
    );

    if (routingOptions.length === 0) continue;

    // Choose tile that best connects toward target
    const dx = tc - col;
    const dy = tr - row;
    const preferH = Math.abs(dx) >= Math.abs(dy);
    const preferDir: Dir = preferH ? (dx > 0 ? 'right' : 'left') : (dy > 0 ? 'down' : 'up');

    // Score tiles: prefer ones connecting toward target
    let bestTile: TileType | null = null;
    let bestScore = -1;
    for (const t of routingOptions) {
      let score = 0;
      if (TILE_CONNECTIONS[t].has(preferDir)) score += 2;
      // Prefer straight tiles over turns
      if (t === 'h' || t === 'v') score += 1;
      if (score > bestScore) {
        bestScore = score;
        bestTile = t;
      }
    }

    if (!bestTile) continue;

    collapseCell(wfc, col, row, bestTile, edgeId);
    const ok = propagate(wfc, col, row);
    if (!ok) return false;

    // Check if we reached the goal
    if (col === goalCol && row === goalRow) return true;

    // Enqueue connected neighbours
    for (const dir of ALL_DIRS) {
      if (!TILE_CONNECTIONS[bestTile].has(dir)) continue;
      const [dc, dr] = DIR_OFFSET[dir];
      const nc = col + dc;
      const nr = row + dr;
      if (!visited.has(key(nc, nr))) {
        const nCell = getWfcCell(wfc, nc, nr);
        if (nCell && nCell.collapsed === null) {
          enqueue(nc, nr);
        }
      }
    }
  }

  return false;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function buildScenarioWfcPath(nodes: NodeDef[], edges: EdgeDef[], padding = 2): ScenarioResult {
  let maxCol = 0;
  let maxRow = 0;
  for (const n of nodes) {
    maxCol = Math.max(maxCol, n.col + n.w);
    maxRow = Math.max(maxRow, n.row + n.h);
  }
  const cols = maxCol + padding + 1;
  const rows = maxRow + padding + 1;

  const wfc = createWfcGrid(cols, rows);

  // Pre-collapse nodes
  for (const n of nodes) {
    for (let r = n.row; r < n.row + n.h; r++) {
      for (let c = n.col; c < n.col + n.w; c++) {
        collapseCell(wfc, c, r, 'node', n.id);
      }
    }
  }

  // Compute and place connections
  const connections = computeConnections(nodes, edges);
  for (const cp of connections) {
    const cell = getWfcCell(wfc, cp.col, cp.row);
    if (cell && cell.collapsed === null) {
      collapseCell(wfc, cp.col, cp.row, 'conn', cp.nodeId);
    }
  }

  // Block corridors
  const connSet = new Set(connections.map(cp => `${cp.row}:${cp.col}`));
  for (const cp of connections) {
    const cellsToBlock: [number, number][] = [];
    if (cp.side === 'left' || cp.side === 'right') {
      const nodeDc = cp.side === 'right' ? -1 : 1;
      const outDc = -nodeDc;
      for (const dc of [nodeDc, 0, outDc]) {
        cellsToBlock.push([cp.col + dc, cp.row - 1]);
        cellsToBlock.push([cp.col + dc, cp.row + 1]);
      }
    } else {
      const nodeDr = cp.side === 'bottom' ? -1 : 1;
      const outDr = -nodeDr;
      for (const dr of [nodeDr, 0, outDr]) {
        cellsToBlock.push([cp.col - 1, cp.row + dr]);
        cellsToBlock.push([cp.col + 1, cp.row + dr]);
      }
    }
    for (const [bc, br] of cellsToBlock) {
      if (connSet.has(`${br}:${bc}`)) continue;
      const cell = getWfcCell(wfc, bc, br);
      if (!cell || cell.collapsed !== null) continue;
      collapseCell(wfc, bc, br, 'blocked', 0);
    }
  }

  // Propagate initial constraints
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (wfc.cells[r]![c]!.collapsed !== null) {
        propagate(wfc, c, r);
      }
    }
  }

  // Route each edge using guided WFC
  const connByEdge = new Map<number, { src: ConnectionPoint | null; tgt: ConnectionPoint | null }>();
  for (const e of edges) connByEdge.set(e.id, { src: null, tgt: null });
  for (const cp of connections) {
    const entry = connByEdge.get(cp.edgeId);
    if (!entry) continue;
    const edge = edges.find(ed => ed.id === cp.edgeId);
    if (!edge) continue;
    if (cp.nodeId === edge.source) entry.src = cp;
    else if (cp.nodeId === edge.target) entry.tgt = cp;
  }

  for (const e of edges) {
    const ep = connByEdge.get(e.id);
    if (!ep?.src || !ep?.tgt) continue;
    growPath(wfc, ep.src.col, ep.src.row, ep.src.side, ep.tgt.col, ep.tgt.row, ep.tgt.side, e.id);
  }

  // Collapse remaining cells to empty
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const cell = wfc.cells[r]![c]!;
      if (cell.collapsed === null) {
        cell.collapsed = 'empty';
        cell.options = new Set(['empty']);
      }
    }
  }

  const grid = wfcToGrid2D(wfc);
  return { grid, nodes, edges, connections };
}
